version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: neptunes_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: neptunes_tix
    ports:
      - "3306:3306"